### ISSUE TITLE
Trojan Alert 

### ISSUE THREAD

**Issue by nelsonwittwer** [HealthTechDevelopers/athena_health#35]
Thanks to HIPAA mandatory anti-virus software, we get this alert when we pull the repository. It doesn't like the file.pdf in the spec fixtures directory. `athena_health/spec/fixtures/file.pdf`. 

Version is current master branch. 

![screen shot 2016-11-21 at 1 41 14 pm](https://cloud.githubusercontent.com/assets/758143/20499793/41b6f638-aff0-11e6-9733-dd9b84b3c33c.png)

[Here is more information about this PDF trojan](https://www.sophos.com/en-us/threat-center/threat-analyses/viruses-and-spyware/Troj~PDFEx-GD/detailed-analysis.aspx)

Sophos seems to think this is a Windows only trojan, but still concerning.

**Comment by MatUrbanski** [comment]
I've added this empty `file.pdf` to test that pdf files are properly handled by the gem and sended to AthenaHealth. You can safely ignore this warining for now, I will fix that.

**Comment by MatUrbanski** [comment]
Fixed via:  18f2744
