### ISSUE TITLE
Best ways to contribute

### ISSUE THREAD

**Issue by panozzaj** [HealthTechDevelopers/athena_health#42]
Hello HealthTechDevelopers! Thanks for publishing this gem, we are finding it very useful so far! We recently started using athenahealth at [OurHealth](https://www.ourhealth.org/) and have a script locally to be able to schedule appointments, cancel them, and list open appointments. We are looking forward to helping maintain it and potentially extend it as it pertains to some core business functionality for us.

I had a few questions that you might help with:

 - Are you open to contributions from the community?
 - What are the best ways to contribute to this gem?
   - My guess would be forking and submitting pull requests and ensuring that the tests pass.
 - Do you have a roadmap or list of outstanding issues or things to clean up anywhere? So far the gem seems to have everything we would need.
 - Any versioning structure or requirements that you have? We'd obviously like to avoid breaking your code with any changes that we propose.

I saw that the wiki had a list of examples, we can try to submit a pull request that links to those in the README or pull them into an examples directory if you want.

**Comment by zywy** [comment]
Hello @panozzaj It's good to hear that you find the gem useful. 

Contributions from the community are very welcome, including but not limited to new endpoints, new/better documentation and refactoring.

Forking  and submitting pull requests is just fine.

There is no specific roadmap and so far features have been added when the community needed them.

As far as versioning is concerned I believe all the versions have been backward compatible so far. If we're going to have breaking changes, I suggest we revisit when we have a pull request.

> I saw that the wiki had a list of examples, we can try to submit a pull request that links to those in the README or pull them into an examples directory if you want.
👍 

Thanks and let us know if the above information is enough to get you started.

**Comment by panozzaj** [comment]
Thanks, that seems great! Thank you for the quick response!

**Comment by lacostenycoder** [comment]
I was trying to add some endpoints and I'm getting authentication errors.
Any advice on how to set up my development configuration to test adding new endpoints?

**Comment by MatUrbanski** [comment]
@lacostenycoder: Do You initialize `AthenaHealth::Client` with proper keys? Please provide more details of the problem.

**Comment by lacostenycoder** [comment]
I have developer credentials but not sure where to initialize them. I
forked the repo, cloned locally, started writing test for new endpoint. You
have VCR cassettes are checked into repo. I follow the standard procedure
to record cassette. It seems the test connection endpoint have hardcoded
placeholder fake keys instead of using environment variables. So where do I
initialize? Thanks.

**Comment by MatUrbanski** [comment]
@lacostenycoder: I was testing new endpoints in the following way:
1. In `spec/support/client.rb` set Your developer keys.
2. Write spec for new endpoint.
3. Run this spec and VCR cassette will be created.
4. Remove your keys and secrets from new VCR cassette that was created.

**Comment by panozzaj** [comment]
FYI I have found the following handy for solving this problem:
https://relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/filter-sensitive-data

Basically you can record cassettes and if VCR finds any of the sensitive
data then it will replace it with placeholders that will be interpolated
when the cassette is run in the future. This cuts down on manual steps and
ensures that you do not accidentally check in keys, and makes it easier for
future people to re-record the cassette if needed.

Usually we specify credentials in a .env file that is git ignored and use
the dotenv gem to read it. This cuts down on ways credentials can get into
git history and makes it easy to filter.

On an unrelated note we are likely moving away from using Ruby for Athena
processing and using an ETL/message bus instead, so I am guessing our
overall involvement will be less than previously anticipated.


On Mar 6, 2017 08:14, "Mateusz Urbański" <notifications@github.com> wrote:

@lacostenycoder <https://github.com/lacostenycoder>: I was testing new
endpoints in the following way:

   1. In spec/support/client.rb set Your developer keys.
   2. Write spec for new endpoint.
   3. Run this spec and VCR cassette will be created.
   4. Remove your keys and secrets from new VCR cassette that was created.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/HealthTechDevelopers/athena_health/issues/42#issuecomment-284392455>,
or mute the thread

**Comment by MatUrbanski** [comment]
@panozzaj: I have plan to implement that in future, thanks for advice :+1:

**Comment by lacostenycoder** [comment]
Thanks everyone.  I normally use .env file and dotenv gem for development. 
Not sure why you have the VCR cassettes checked in in the first place.
Wouldn't it be much simpler to not check them in at all and use env vars for all credentials?
Having to change code to run tests seems cumbersome.

**Comment by panozzaj** [comment]
@lacostenycoder Thanks for writing! This is just my opinion, but it helps us a lot on other projects to have the cassettes checked in. This ensures that you can easily replay requests and not need to hit the network. Otherwise the tests can be slow, flaky (due to network connections), dependent on having your third-party environment (athenahealth sandbox) set up correctly and consistently, will actually delete or update items in your third-party environment, etc.

http://stackoverflow.com/questions/17951114/is-it-correct-to-store-vcr-cassettes-in-repository seems to suggest that checking them in a decent practice.

One example (might not be the best) is at https://github.com/HealthTechDevelopers/athena_health/blob/master/spec/fixtures/vcr_cassettes/cancel_check_in.yml and https://github.com/HealthTechDevelopers/athena_health/blob/08f56da9042efa1e41dff60f08b59762dab10324/spec/lib/endpoints/appointments_spec.rb#L267 . You would have to replicate the entire environment, ids and all, in your local machine to get that test to pass without the VCR cassette. Having all of the state in the third-party tool probably makes the cassette harder to re-record, but if you change the underlying code at least you have a regression test. (The test in this case does not assert much on the values that are returned, but I could imagine how it might do so.) Another approach might be to use something like Webmock, but it seems like VCR is a decent choice for this.

> Having to change code to run tests seems cumbersome.

I'm not sure I fully understand, what code would you have to change to run the tests? Sorry that I am missing what you are saying.

**Comment by lacostenycoder** [comment]
@panozzaj @MatUrbanski 

In Mat's previous comment his instructions are to:

> In spec/support/client.rb set Your developer keys.

This means having to change code in order to run a new spec  which will need to create a new VCR cassette.  I propose to at least substitute in environment variables.
I add this a new branch and will send PR shortly.  Thanks.

**Comment by panozzaj** [comment]
Sounds great, thanks!
